name: Auto Issue Reaction

on:
  issue_comment:
    types:
      - created

jobs:
  comment-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install --save axios
      - name: Comment Issue
        uses: actions/github-script@v4
        with:
          script: |
            const {owner, repo} = context.issue
            github.reactions.createForIssueComment({
              owner,
              repo,
              comment_id: context.payload.comment.id,
              content: "+1",
            });            
            github.issues.createComment({
              issue_number: context.issue.number,
              owner,
              repo,
              body: "Hello",
            });
            const axios = require('axios');
            
            const json = JSON.stringify({ answer: 42 });
            const res = await axios.post('https://httpbin.org/post', json, {
              headers: {
                'Content-Type': 'application/json'
              }
            })
              .catch(err => {
                console.log('Error: ', err.message);
              });
            console.log('Response: ', res.data.data);


