name: Auto Issue Reaction

on:
  issue_comment:
    types:
      - created

jobs:
  comment-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Comment Issue
        uses: actions/github-script@v4
        with:
          script: |
            const {issue_number, owner, repo} = context.issue
            github.reactions.createForIssueComment({
              owner,
              repo,
              comment_id: context.payload.comment.id,
              content: "+1",
            });            
            github.issues.createComment({
              issue_number,
              owner,
              repo,
              body: "Hello",
            });
