name: Auto Issue Reaction

on:
  issue_comment:
    types:
      - created

jobs:
  comment-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Comment Issue
        uses: actions/github-script@v4
        with:
          script: |
            const {owner, repo} = context.issue
            github.reactions.createForIssueComment({
              owner,
              repo,
              comment_id: context.payload.comment.id,
              content: "+1",
            });            
            github.issues.createComment({
              issue_number: context.issue.number,
              owner,
              repo,
              body: "Hello",
            });
            const axios = require('axios');

            axios.get('https://jsonplaceholder.typicode.com/users')
              .then(res => {
                const headerDate = res.headers && res.headers.date ? res.headers.date : 'no response date';
                console.log('Status Code:', res.status);
                console.log('Date in Response header:', headerDate);

                const users = res.data;

                for(user of users) {
                  console.log(`Got user with id: ${user.id}, name: ${user.name}`);
                }
              })
              .catch(err => {
                console.log('Error: ', err.message);
              });
