name: Auto Issue Reaction

on:
  issue_comment:
    types:
      - created

jobs:
  comment-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install --save axios
      - name: Comment Issue
        uses: actions/github-script@v4
        with:
          script: |
            const {owner, repo} = context.issue
            github.reactions.createForIssueComment({
              owner,
              repo,
              comment_id: context.payload.comment.id,
              content: "+1",
            });            
            const axios = require('axios');            
            const json = '{"prompt": "A neutron star is the collapsed core of a massive supergiant star, which had a total mass of between 10 and 25 solar masses, possibly more if the star was especially metal-rich. Neutron stars are the smallest and densest stellar objects, excluding black holes and hypothetical white holes, quark stars, and strange stars. Neutron stars have a radius on the order of 10 kilometres (6.2 mi) and a mass of about 1.4 solar masses. They result from the supernova explosion of a massive star, combined with gravitational collapse, that compresses the core past white dwarf star density to that of atomic nuclei.\n\nAnswer the following question from the text above.\n\nQ: How are neutron stars created?\nA: ", "max_tokens": 256, "temperature": 0.7, "frequency_penalty": 0, "presence_penalty": 0, "top_p": 1, "stop": ["\n"]}';
            const res = await axios.post('https://alexvieiopenai.openai.azure.com/openai/deployments/model1/completions?api-version=2022-12-01', json, {
              headers: {
                'Content-Type': 'application/json',
                'api-key': '382b38480e484dcba23faac421612697'
              }
            })
              .catch(err => {
                console.log('Error: ', err.message);
              });
            console.log('Response: ', res.data.id);
            github.issues.createComment({
              issue_number: context.issue.number,
              owner,
              repo,
              body: "Hello",
            });

